# Generated by Django 3.0.3 on 2020-03-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("idmyteamserver", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="allow_storage",
            new_name="storeimage",
        ),
    ]
