# Generated by Django 3.0.3 on 2020-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idmyteamserver", "0003_auto_20200330_1652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
