# Generated by Django 3.1.2 on 2020-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idmyteamserver", "0004_auto_20200331_1349"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
