#!/bin/sh

#sql=$(ssh root@idmy.team 'export SETTINGS_FILE=/var/www/conf/prod_remote.yaml && export PYTHONPATH=/var/www/settings/:$PYTHONPATH && cd /var/www/ && python helpers/dump_schema.py')
#echo "$sql" > 'db/schema.sql'

export SETTINGS_FILE="$(pwd)/conf/test_local.conf"
export PYTHONPATH="$(pwd)/:$(pwd)/web/:$(pwd)/settings/:$(pwd)/helpers/"
echo $PYTHONPATH
#$(which python) helpers/*.py

exit $?