repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variable' ]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports
  #- repo: https://gitlab.com/pycqa/flake8
  #  hooks:
  #  - id: flake8
  #    args: ["--config=setup.cfg"]
  #    language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        language: system
        name: Run MyPy typing checks.
        entry: bash -c "PYTHONPATH=$(pwd):$PYTHONPATH mypy ."
        pass_filenames: false
        verbose: true
        types: [ "python" ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: bash -c "./manage.py makemigrations --check --dry-run"
        types: [ "python" ]
        pass_filenames: false