language: python

python:
  - "3.6"

install:
  - pip install -r travis_requirements.txt

cache: pip

script: python -m pytest

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE `idmyteam`;' # matches env

env:
  global:
    - PYTHONPATH=${TRAVIS_BUILD_DIR}/settings/:${TRAVIS_BUILD_DIR}/web/:$PYTHONPATH
    - CONF=/conf/test_travis.conf