language: python

python:
  - "3.6"

install:
  - pip install -r travis_requirements.txt

cache: pip

script: python -m pytest

env:
  global:
    - PYTHONPATH=${TRAVIS_BUILD_DIR}/settings/:${TRAVIS_BUILD_DIR}/web/:$PYTHONPATH
    - CONF=/conf/test_local.conf