version: '3.2'

services:
  recognition-worker:
    build:
      context: "./ML/"
    depends_on:
      - redis

  db:
    image: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: idmyteam
      MYSQL_USER: idmyteam
      MYSQL_PASSWORD: idmyteam
    tty: true

  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"
    entrypoint: redis-server --appendonly yes
