version: '3.2'

services:
  recognition-worker:
    build:
      context: "./ML/"
    depends_on:
      - redis

  web:
    build:
      context: "./web/"
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - "./web/.env"
    environment:
      DATABASE_USER: idmyteam
      DATABASE_PASS: idmyteam
      DATABASE_NAME: idmyteam
      DATABASE_HOST: db
      JAEGER_COLLECTOR_HOST_NAME: jaeger
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DATABASE: idmyteam
      POSTGRES_USER: idmyteam
      POSTGRES_PASSWORD: idmyteam
    tty: true

  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"
    entrypoint: redis-server --appendonly yes

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:14268:14268"
