version: '3.8'
services:
  web:
    image: maxisme/idmyteam-server:tornado-to-django # temporary test
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - "web/.env"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.idmyteam.rule=Host(`idmy.team`)"
        - "traefik.http.routers.idmyteam.entrypoints=web-secure"
        - "traefik.http.routers.idmyteam.tls.certresolver=letsencrypt"
        - "traefik.http.services.idmyteam.loadbalancer.server.port=8000"
        - "traefik.http.routers.idmyteam.middlewares=404"
    volumes:
      - static_volume:/usr/src/app/static/
    networks:
      - traefik
      - db
      - tracing

  static:
    image: nginx
    volumes:
      - static_volume:/usr/share/nginx/html:ro
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.idmyteam-static.rule=Host(`idmy.team`) && PathPrefix(`/static/`)"
        - "traefik.http.routers.idmyteam-static.entrypoints=web-secure"
        - "traefik.http.routers.idmyteam-static.tls.certresolver=letsencrypt"
        - "traefik.http.services.idmyteam-static.loadbalancer.server.port=80"
        - "traefik.http.routers.idmyteam-static.middlewares=404"
    networks:
      - traefik

networks:
  traefik:
    external: true
  db:
    external: true
  tracing:
    external: true

volumes:
  static_volume: