version: '3.8'
services:
  web:
    image: maxisme/idmyteam-server
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - "web/.env"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.idmyteam.rule=Host(`idmy.team`)"
        - "traefik.http.services.idmyteam.loadbalancer.server.port=8000"
        - "traefik.http.routers.idmyteam.middlewares=404"
    volumes:
      - type: volume
        source: volume_static
        target: /usr/src/app/static
        volume:
          nocopy: false
    networks:
      - traefik
      - db
      - tracing
      - logging

  migrations:
    image: maxisme/idmyteam-server
    env_file:
      - "web/.env"
    command: python manage.py migrate
    networks:
      - db

  static:
    image: nginx
    volumes:
      - type: volume
        source: volume_static
        target: /usr/share/nginx/html/static
        read_only: true
        volume:
          nocopy: true
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.idmyteam-static.rule=Host(`idmy.team`) && PathPrefix(`/static/`)"
        - "traefik.http.services.idmyteam-static.loadbalancer.server.port=80"
        - "traefik.http.routers.idmyteam-static.middlewares=404"
    networks:
      - traefik

networks:
  traefik:
    external: true
  db:
    external: true
  tracing:
    external: true
  logging:
    external: true

volumes:
  volume_static: