name: ID My Team Server
on: [push]
jobs:
    publish-pypi:
      name: Publish PyPi
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: '0'

        - name: Bump version and push tag
          id: version
          uses: anothrNick/github-tag-action@1.33.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Build dists
          env:
            VERSION: ${{ steps.version.outputs.new_tag }}
          run: |
            pip3 install setuptools wheel
            python3 web/idmyteam/setup.py sdist bdist_wheel
        - name: Publish package to PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.PYPI_TOKEN }}
            verify_metadata: false
            verbose: true
