name: ID My Team Server
on: [push]
jobs:

  publish-pypi:
    name: Publish PyPi
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build dists
        env:
          VERSION: jobs.version.new_tag
        run: |
          pip install setuptools
          cd web/idmyteam/
          python3 setup.py sdist bdist_wheel
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: maxisme
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: web/idmyteam/
          verify_metadata: false
          verbose: true
