name: ID My Team Server
on: [push]
jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [3.6, 3.7, 3.8]
#
#    steps:
#    - uses: actions/checkout@v1
#
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v1
#      with:
#        python-version: ${{ matrix.python-version }}
#
#    - name: Fetch cached dependencies
#      uses: actions/cache@v1
#      with:
#        path: ~/.cache/pip
#        key: ${{ runner.os }}-pip-${{ hashFiles('**/test_requirements.txt') }}
#        restore-keys: |
#          ${{ runner.os }}-pip-
#
#    - name: Install dependencies
#      run: |
#        sudo apt-get install libmysqlclient-dev
#        python -m pip install --upgrade pip
#        pip install -r test_requirements.txt # --cache-dir ~/.pip-cache
#
#    - name: Test
#      run: |
#        export CONF='/conf/test_actions.conf'
#        export PYTHONPATH="$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/settings/:$GITHUB_WORKSPACE/web/:$GITHUB_WORKSPACE"
#        pytest

  publish:
    name: Publish Docker image
#    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Publish to Docker Registry
        uses: docker/build-push-action@v1
        with:
          path: "web/"
          cache_froms: python:3
          repository: ${{ github.repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true
#      - name: Update Swarm
#        if: github.ref == 'refs/heads/master'
#        run: |
#          export sha="${{ github.sha }}"
#          curl -f -X POST ${{ secrets.SWARM_HOOK }} \
#          -H 'Content-Type: application/x-www-form-urlencoded' \
#          -d 'service=notifi-backend_app' \
#          -d "image=${{ github.repository }}" \
#          -d "tag=sha-${sha:0:7}" \
#          -d "token=${{ secrets.HOOK_TOKEN }}"

