name: ID My Team Server
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: pre-commit/action@v2.0.0

      - name: Test web
        run: |
          docker-compose up test-web

      - name: Upload web coverage to Codecov
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  publish-pypi:
    name: Publish PyPi
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build dists
        run: |
          pip3 install setuptools
          sed -i -e "s/REPLACEDINCI/${{ steps.version.outputs.new_tag }}/g" web/idmyteam/idmyteam/__init__.py
          cd web/idmyteam/
          python3 setup.py sdist
          
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verify_metadata: false
          verbose: true
          packages_dir: web/idmyteam/dist

  build:
    name: Publish Docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: Publish to Docker Registry
        uses: docker/build-push-action@v1
        with:
          path: "web/"
          repository: ${{ github.repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true
          build_args: COMMIT_HASH=${{ github.sha }}

  deploy:
    needs: build
    #if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-helm@v1
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Upgrade helm
        run: |
          # pull infra charts
          helm repo add maxisme https://${{ secrets.GH_PA_TOKEN }}@raw.githubusercontent.com/maxisme/infra/master/k8s/charts/
          helm repo update

          # create kube config
          mkdir ~/.kube
          echo "${{ secrets.B64_KUBE_CONFIG }}" | base64 --decode > ~/.kube/config

          # deploy helms
          repo="${{ github.repository }}"
          helm upgrade "${repo//./}" maxisme/web -f helm-values.yml --set="image.tag=sha-${GITHUB_SHA::7}" --atomic --timeout 120s

          # clean up
          rm ~/.kube/config
